### ISSUE TITLE
Todo.txt cannot find folder list from Dropbox

### ISSUE THREAD

**Issue by derivs1** [todotxt/todo.txt-android#426]
I purchased todo.txtx on android and I keep getting the message when I select "File Location" 
"failed to load folder list from Dropbox"

I can't get any further and can't specify a location

Can anyone help please

**Comment by rumbero71** [comment]
Hi, same problem here. Huawei P8 Lite, Android 6.0 updated today, Dropbox App 64.2.2, Todo.txt v2.2. Logged out, logging in->does not work. Reinstalled app->Does not work. Logged out and back in again (feels like The IT Crowd at this point ;-) )->does not work.
Any hints ?

**Comment by dszkola** [comment]
My guess is she was using Dropbox API v1 because it went out of service today:

As previously announced, API v1 is being retired on Thursday, September 28th, 2017.

On this date, API v1 endpoints will return a 400 error with this message: {“error”: “v1_retired”}. This means any integrations or applications still relying on API v1 endpoints may stop working.

If you still have not migrated to v2, check out the migration guide for more details.

We built API v2 to create a more consistent, simplified, and scalable platform for developers, and we appreciate your patience and flexibility as we make this transition.

So an updated app will be required to fix this issue. I also noticed this morning that the app no longer syncs with Dropbox.

**Comment by aput** [comment]
I have the same error message since one or two days:  "Synchronization failed".
Thanks to this forum I know I am not the only one.
What can I do now to get this working, other than wait for a new Todo.txt release?

**Comment by kie27** [comment]
I have just upgraded phones, and am using v2.2 on a samsung note 8, it was working with my previous phone and syncing with my Desktop. It no longer works with my new phone.
I get synchronising failed, when clicking on file location it says Failed to load folder list from Dropbox.
I have given it the relevant permissions from Dropbox and tried all the logging in and out etc. :(

**Comment by mathewjowens** [comment]
Yep, another one with the same issue.

Been successfully using todo.txt on both Windows desktop and Android phone for a while. But it recently stopped working on my phone. Can't synchronise, then when I try point point the Android app to the todo.txt file location within Dropbox, I get "Failed to load folder list from Dropbox."

**Comment by pescegiallo** [comment]
What's the problem? With Android 6.0.1 I get this error: "Failed to load folder list from Dropbox" and with iOS 10.3.3: "There was an error uploading your todo.txt file." Any tipps?

**Comment by dszkola** [comment]
The problem is that at least the Dropbox portion of the code has not been updated in quite some time and uses v1 of the Dropbox API. Dropbox turned off access for this API on 9/28/2017. Until someone updates the code to use v2 of the Dropbox API, you will no longer be able to use this app.

**Comment by Elangco** [comment]
Well thank you Dropbox. :(

Having said that: on the PC todo.txt just needs access to a shared folder, no proprietary API needed or anything like that. It would be very cool if the next version of todo.txt on Android could be like that. We could use any file synching method we like then. Bye bye Dropbox!
