### ISSUE TITLE
Alternatives to Dropbox

### ISSUE THREAD

**Issue by galan** [todotxt/todo.txt-android#460]
Due to security concerns alternatives to dropbox should be implemented. There are plenty of other free systems out there, eg. seafile or owncloud.

**Comment by theScrabi** [comment]
Creating such a great opne source software, but than not making it possible for the user to decide his service is to be honest a little bit pure, although I understand your concerns.

However at lease ownCloud could be supported, since as galan said it, from a securety point of view this solution fails completely.

However [here](https://blog.portknox.net/2014/how-to-manage-todotxt-with-owncloud) is a solution for using todo.txt with ownCloud (and other sync tools), although it can't be used with this app.
